-- SPDX-License-Identifier: PostgreSQL
-- The four shared recursive-entry DML trigger functions. Installed by
-- CREATE EXTENSION, so they are owned by the extension installer. A
-- chunked invalidation needs DELETE on the managed destination, DELETE
-- on postvec.jobs/jobs_dead, and INSERT of an `op` column PUBLIC has no
-- grant on, none of which an application writer holds. The registry id
-- arrives in TG_ARGV[0]; per-entry identity (destination, PK/source
-- columns) is read from postvec.registry inside the pinned pg_catalog
-- search path, and every identifier goes through quote_ident /
-- format('%I'). Per-entry DDL is only CREATE TRIGGER.
--
-- Confused-deputy check (same as trg_truncate): the firing relation must
-- be the recursive registry row's source relation, else WARNING + RETURN
-- NULL. Without it any table owner could attach a function to their own
-- table with a victim's registry id and purge the victim's chunks and
-- jobs.
--
-- The UPDATE function's statement-mode change set arrives as TG_ARGV[1..]
-- (referenced column names, regenerated by set_format()). Each is
-- rendered through format('%I'), so the arguments can only select which
-- columns are compared, never inject SQL. Attaching triggers requires
-- TRIGGER privilege on the table, which is already table-owner trust.
--
-- Job hygiene inside the invalidation is asymmetric:
--   - child embed jobs (op='embed') for the document are deleted, pending
--     or claimed. A claimed child holds no row lock (its claim transaction
--     committed before inference) and its write-back is a chunk-keyed
--     obsolete no-op either way.
--   - a pending refresh job is left for the dedup index to coalesce with
--     the one this invalidation enqueues. Deleting and re-inserting the
--     same pending-dedup key inside one statement would race its own
--     ON CONFLICT arbitration (the deleted row is still index-visible to
--     the command).
--   - a claimed refresh job is never touched: the refresh worker holds
--     that row's lock inside the one transaction that processes it while
--     it waits FOR SHARE on the source row this trigger's statement has
--     locked. Deleting it here would deadlock. It self-resolves: the
--     refresh re-reads the committed source state.
--   - dead rows for the document are deleted wholesale (their input is
--     superseded), except on plain content updates where the enqueued
--     refresh replaces them anyway.

CREATE OR REPLACE FUNCTION postvec.trg_chunk_ins() RETURNS trigger LANGUAGE plpgsql
SECURITY DEFINER SET search_path = pg_catalog AS $body$
DECLARE
    r record;
    rid bigint := TG_ARGV[0]::bigint;
BEGIN
    SELECT reg.source_column, reg.pk_columns[1] AS pk_col
      INTO r
      FROM postvec.registry reg
     WHERE reg.id = rid
       AND reg.chunking = 'recursive'
       AND (
            (reg.table_schema = TG_TABLE_SCHEMA::text
                 AND reg.table_name = TG_TABLE_NAME::text)
            -- Row triggers are cloned to partitions, where the firing
            -- relation is the partition itself; any relation inside the
            -- registered source's partition tree is that source. Attaching
            -- a partition requires ownership of both sides, so this widens
            -- nothing an attacker can reach.
            OR EXISTS (
                SELECT 1 FROM pg_catalog.pg_partition_tree(
                    pg_catalog.to_regclass(
                        pg_catalog.quote_ident(reg.table_schema) || '.' ||
                        pg_catalog.quote_ident(reg.table_name))) pt
                 WHERE pt.relid = TG_RELID)
       );
    IF NOT FOUND THEN
        RAISE WARNING 'postvec: trg_chunk_ins(%) fired on %.%, which is not that recursive registry entry''s table; ignoring',
            TG_ARGV[0], TG_TABLE_SCHEMA, TG_TABLE_NAME;
        RETURN NULL;
    END IF;
    IF TG_LEVEL = 'STATEMENT' THEN
        EXECUTE pg_catalog.format(
            'INSERT INTO postvec.jobs (registry_id, pk_value, op)
             SELECT $1, n.%1$I::text, ''refresh'' FROM new_table n
              WHERE n.%2$I IS NOT NULL
             ON CONFLICT (registry_id, op, pk_value, chunk_id)
             WHERE claimed_at IS NULL DO NOTHING',
            r.pk_col, r.source_column) USING rid;
    ELSE
        EXECUTE pg_catalog.format(
            'INSERT INTO postvec.jobs (registry_id, pk_value, op)
             SELECT $1, ($2).%1$I::text, ''refresh''
              WHERE ($2).%2$I IS NOT NULL
             ON CONFLICT (registry_id, op, pk_value, chunk_id)
             WHERE claimed_at IS NULL DO NOTHING',
            r.pk_col, r.source_column) USING rid, NEW;
    END IF;
    PERFORM postvec.worker_kick();
    RETURN NULL;
END $body$;

CREATE OR REPLACE FUNCTION postvec.trg_chunk_upd() RETURNS trigger LANGUAGE plpgsql
SECURITY DEFINER SET search_path = pg_catalog AS $body$
DECLARE
    r record;
    rid bigint := TG_ARGV[0]::bigint;
    pred text := '';
    i int;
BEGIN
    SELECT reg.source_column, reg.pk_columns[1] AS pk_col,
           pg_catalog.quote_ident(reg.destination_schema) || '.' ||
           pg_catalog.quote_ident(reg.destination_table) AS qdest
      INTO r
      FROM postvec.registry reg
     WHERE reg.id = rid
       AND reg.chunking = 'recursive'
       AND (
            (reg.table_schema = TG_TABLE_SCHEMA::text
                 AND reg.table_name = TG_TABLE_NAME::text)
            -- Row triggers are cloned to partitions, where the firing
            -- relation is the partition itself; any relation inside the
            -- registered source's partition tree is that source. Attaching
            -- a partition requires ownership of both sides, so this widens
            -- nothing an attacker can reach.
            OR EXISTS (
                SELECT 1 FROM pg_catalog.pg_partition_tree(
                    pg_catalog.to_regclass(
                        pg_catalog.quote_ident(reg.table_schema) || '.' ||
                        pg_catalog.quote_ident(reg.table_name))) pt
                 WHERE pt.relid = TG_RELID)
       );
    IF NOT FOUND THEN
        RAISE WARNING 'postvec: trg_chunk_upd(%) fired on %.%, which is not that recursive registry entry''s table; ignoring',
            TG_ARGV[0], TG_TABLE_SCHEMA, TG_TABLE_NAME;
        RETURN NULL;
    END IF;
    IF TG_LEVEL = 'STATEMENT' THEN
        IF TG_NARGS < 2 THEN
            pred := pg_catalog.format('n.%1$I IS DISTINCT FROM o.%1$I', r.source_column);
        ELSE
            FOR i IN 1 .. TG_NARGS - 1 LOOP
                IF i > 1 THEN pred := pred || ' OR '; END IF;
                pred := pred || pg_catalog.format('n.%1$I IS DISTINCT FROM o.%1$I', TG_ARGV[i]);
            END LOOP;
        END IF;
        EXECUTE pg_catalog.format(
            'WITH changed AS (
                 SELECT n.%1$I AS pk, n.%2$I AS src
                   FROM new_table n JOIN old_table o ON o.%1$I = n.%1$I
                  WHERE %4$s
             ), dc AS (
                 DELETE FROM %3$s c USING changed x
                  WHERE c.postvec_source_pk = x.pk
             ), dj AS (
                 DELETE FROM postvec.jobs j USING changed x
                  WHERE j.registry_id = $1 AND j.op = ''embed''
                    AND j.pk_value = x.pk::text
             ), dd AS (
                 DELETE FROM postvec.jobs_dead j USING changed x
                  WHERE j.registry_id = $1 AND j.pk_value = x.pk::text
             )
             INSERT INTO postvec.jobs (registry_id, pk_value, op)
             SELECT $1, x.pk::text, ''refresh'' FROM changed x
              WHERE x.src IS NOT NULL
             ON CONFLICT (registry_id, op, pk_value, chunk_id)
             WHERE claimed_at IS NULL DO NOTHING',
            r.pk_col, r.source_column, r.qdest, pred) USING rid;
    ELSE
        -- Row mode: the trigger's OF-list/WHEN guard already restricted this
        -- firing to real referenced-column changes.
        EXECUTE pg_catalog.format(
            'WITH dc AS (
                 DELETE FROM %3$s c WHERE c.postvec_source_pk = ($2).%1$I
             ), dj AS (
                 DELETE FROM postvec.jobs j
                  WHERE j.registry_id = $1 AND j.op = ''embed''
                    AND j.pk_value = ($2).%1$I::text
             ), dd AS (
                 DELETE FROM postvec.jobs_dead j
                  WHERE j.registry_id = $1 AND j.pk_value = ($2).%1$I::text
             )
             INSERT INTO postvec.jobs (registry_id, pk_value, op)
             SELECT $1, ($3).%1$I::text, ''refresh''
              WHERE ($3).%2$I IS NOT NULL
             ON CONFLICT (registry_id, op, pk_value, chunk_id)
             WHERE claimed_at IS NULL DO NOTHING',
            r.pk_col, r.source_column, r.qdest) USING rid, OLD, NEW;
    END IF;
    PERFORM postvec.worker_kick();
    RETURN NULL;
END $body$;

-- PK-change companion: always row-level (both trigger modes), fired WHEN the
-- PK actually changed. The OLD identity's whole chunk set and queue state are
-- obsolete (including any pending refresh keyed by the old rendering — its
-- key differs from the NEW-keyed insert, so deleting it is arbitration-safe);
-- the NEW identity gets one refresh when the source is non-NULL.
CREATE OR REPLACE FUNCTION postvec.trg_chunk_pk() RETURNS trigger LANGUAGE plpgsql
SECURITY DEFINER SET search_path = pg_catalog AS $body$
DECLARE
    r record;
    rid bigint := TG_ARGV[0]::bigint;
BEGIN
    SELECT reg.source_column, reg.pk_columns[1] AS pk_col,
           pg_catalog.quote_ident(reg.destination_schema) || '.' ||
           pg_catalog.quote_ident(reg.destination_table) AS qdest
      INTO r
      FROM postvec.registry reg
     WHERE reg.id = rid
       AND reg.chunking = 'recursive'
       AND (
            (reg.table_schema = TG_TABLE_SCHEMA::text
                 AND reg.table_name = TG_TABLE_NAME::text)
            -- Row triggers are cloned to partitions, where the firing
            -- relation is the partition itself; any relation inside the
            -- registered source's partition tree is that source. Attaching
            -- a partition requires ownership of both sides, so this widens
            -- nothing an attacker can reach.
            OR EXISTS (
                SELECT 1 FROM pg_catalog.pg_partition_tree(
                    pg_catalog.to_regclass(
                        pg_catalog.quote_ident(reg.table_schema) || '.' ||
                        pg_catalog.quote_ident(reg.table_name))) pt
                 WHERE pt.relid = TG_RELID)
       );
    IF NOT FOUND THEN
        RAISE WARNING 'postvec: trg_chunk_pk(%) fired on %.%, which is not that recursive registry entry''s table; ignoring',
            TG_ARGV[0], TG_TABLE_SCHEMA, TG_TABLE_NAME;
        RETURN NULL;
    END IF;
    EXECUTE pg_catalog.format(
        'WITH dc AS (
             DELETE FROM %3$s c WHERE c.postvec_source_pk = ($2).%1$I
         ), dj AS (
             DELETE FROM postvec.jobs j
              WHERE j.registry_id = $1 AND j.pk_value = ($2).%1$I::text
                AND NOT (j.op = ''refresh'' AND j.claimed_at IS NOT NULL)
         ), dd AS (
             DELETE FROM postvec.jobs_dead j
              WHERE j.registry_id = $1 AND j.pk_value = ($2).%1$I::text
         )
         INSERT INTO postvec.jobs (registry_id, pk_value, op)
         SELECT $1, ($3).%1$I::text, ''refresh''
          WHERE ($3).%2$I IS NOT NULL
         ON CONFLICT (registry_id, op, pk_value, chunk_id)
         WHERE claimed_at IS NULL DO NOTHING',
        r.pk_col, r.source_column, r.qdest) USING rid, OLD, NEW;
    PERFORM postvec.worker_kick();
    RETURN NULL;
END $body$;

CREATE OR REPLACE FUNCTION postvec.trg_chunk_del() RETURNS trigger LANGUAGE plpgsql
SECURITY DEFINER SET search_path = pg_catalog AS $body$
DECLARE
    r record;
    rid bigint := TG_ARGV[0]::bigint;
BEGIN
    SELECT reg.pk_columns[1] AS pk_col,
           pg_catalog.quote_ident(reg.destination_schema) || '.' ||
           pg_catalog.quote_ident(reg.destination_table) AS qdest
      INTO r
      FROM postvec.registry reg
     WHERE reg.id = rid
       AND reg.chunking = 'recursive'
       AND (
            (reg.table_schema = TG_TABLE_SCHEMA::text
                 AND reg.table_name = TG_TABLE_NAME::text)
            -- Row triggers are cloned to partitions, where the firing
            -- relation is the partition itself; any relation inside the
            -- registered source's partition tree is that source. Attaching
            -- a partition requires ownership of both sides, so this widens
            -- nothing an attacker can reach.
            OR EXISTS (
                SELECT 1 FROM pg_catalog.pg_partition_tree(
                    pg_catalog.to_regclass(
                        pg_catalog.quote_ident(reg.table_schema) || '.' ||
                        pg_catalog.quote_ident(reg.table_name))) pt
                 WHERE pt.relid = TG_RELID)
       );
    IF NOT FOUND THEN
        RAISE WARNING 'postvec: trg_chunk_del(%) fired on %.%, which is not that recursive registry entry''s table; ignoring',
            TG_ARGV[0], TG_TABLE_SCHEMA, TG_TABLE_NAME;
        RETURN NULL;
    END IF;
    IF TG_LEVEL = 'STATEMENT' THEN
        EXECUTE pg_catalog.format(
            'WITH gone AS (
                 SELECT o.%1$I AS pk FROM old_table o
             ), dc AS (
                 DELETE FROM %2$s c USING gone x
                  WHERE c.postvec_source_pk = x.pk
             ), dj AS (
                 DELETE FROM postvec.jobs j USING gone x
                  WHERE j.registry_id = $1 AND j.pk_value = x.pk::text
                    AND NOT (j.op = ''refresh'' AND j.claimed_at IS NOT NULL)
             )
             DELETE FROM postvec.jobs_dead j USING gone x
              WHERE j.registry_id = $1 AND j.pk_value = x.pk::text',
            r.pk_col, r.qdest) USING rid;
    ELSE
        EXECUTE pg_catalog.format(
            'WITH dc AS (
                 DELETE FROM %2$s c WHERE c.postvec_source_pk = ($2).%1$I
             ), dj AS (
                 DELETE FROM postvec.jobs j
                  WHERE j.registry_id = $1 AND j.pk_value = ($2).%1$I::text
                    AND NOT (j.op = ''refresh'' AND j.claimed_at IS NOT NULL)
             )
             DELETE FROM postvec.jobs_dead j
              WHERE j.registry_id = $1 AND j.pk_value = ($2).%1$I::text',
            r.pk_col, r.qdest) USING rid, OLD;
    END IF;
    RETURN NULL;
END $body$;

-- EXECUTE stays granted (explicitly, not via default privileges):
-- PostgreSQL requires the role issuing CREATE TRIGGER (the table owner
-- inside a non-superuser enable()) to hold EXECUTE on the trigger
-- function. A trigger-returning function cannot be called as an ordinary
-- function, and the firing-relation/registry deputy check above is the
-- security boundary.
GRANT EXECUTE ON FUNCTION postvec.trg_chunk_ins() TO PUBLIC;
GRANT EXECUTE ON FUNCTION postvec.trg_chunk_upd() TO PUBLIC;
GRANT EXECUTE ON FUNCTION postvec.trg_chunk_pk() TO PUBLIC;
GRANT EXECUTE ON FUNCTION postvec.trg_chunk_del() TO PUBLIC;

-- Shared TRUNCATE trigger function: registry id arrives via TG_ARGV[0].
-- Purges pending (unclaimed) jobs for the entry when its table is truncated.
-- SECURITY DEFINER (owned by the extension-installing superuser): the
-- truncating role must not need DELETE on postvec.jobs. search_path is pinned
-- as SECURITY DEFINER hygiene demands.
--
-- Deputy check: plpgsql functions are PUBLIC-executable by default, so any
-- table owner could attach this function to their own table with a victim's
-- registry id as TG_ARGV[0] and purge the victim's pending jobs by TRUNCATEing
-- their own table. The firing relation must therefore match the registry row
-- the argument names; anything else is ignored with a WARNING.
CREATE OR REPLACE FUNCTION postvec.trg_truncate() RETURNS trigger LANGUAGE plpgsql
SECURITY DEFINER SET search_path = pg_catalog AS $body$
DECLARE
    r record;
BEGIN
    SELECT reg.chunking, reg.destination_schema, reg.destination_table
      INTO r
      FROM postvec.registry reg
     WHERE reg.id = TG_ARGV[0]::bigint
       AND reg.table_schema = TG_TABLE_SCHEMA::text
       AND reg.table_name = TG_TABLE_NAME::text;
    IF NOT FOUND THEN
        RAISE WARNING 'postvec: trg_truncate(%) fired on %.%, which is not that registry entry''s table; ignoring',
            TG_ARGV[0], TG_TABLE_SCHEMA, TG_TABLE_NAME;
        RETURN NULL;
    END IF;
    IF r.chunking = 'recursive' THEN
        -- A truncated source has no rows, so every chunk, queued job and
        -- dead letter for the entry is obsolete. Claimed refresh rows are
        -- skipped: the refresh worker holds a lock on that row in the one
        -- transaction that processes it while waiting FOR SHARE on the
        -- source. Deleting it here would deadlock; it self-resolves by
        -- finding the source row gone. Claimed child embeds hold no lock
        -- (the claim transaction committed before inference) and their
        -- write-back is a chunk-keyed obsolete no-op either way.
        EXECUTE pg_catalog.format('DELETE FROM %I.%I',
                                  r.destination_schema, r.destination_table);
        DELETE FROM postvec.jobs
         WHERE registry_id = TG_ARGV[0]::bigint
           AND NOT (op = 'refresh' AND claimed_at IS NOT NULL);
        DELETE FROM postvec.jobs_dead
         WHERE registry_id = TG_ARGV[0]::bigint;
    ELSE
        DELETE FROM postvec.jobs
         WHERE registry_id = TG_ARGV[0]::bigint
           AND claimed_at IS NULL;
    END IF;
    DELETE FROM postvec.lexical_stats WHERE registry_id = TG_ARGV[0]::bigint;
    PERFORM postvec.worker_kick();
    RETURN NULL;
END $body$;
